-- Forward-only RunningHub discovery/workflow facts. No physical foreign keys or configuration snapshots.
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS av_discovery_banner (banner_id BIGINT NOT NULL, title VARCHAR(128) NOT NULL, image_oss_id BIGINT NULL, link_url VARCHAR(512) NULL, sort_order INT NOT NULL DEFAULT 0, status VARCHAR(16) NOT NULL DEFAULT 'active', create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (banner_id), CHECK (status IN ('active','inactive'))) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS av_discovery_category (category_id BIGINT NOT NULL, name VARCHAR(64) NOT NULL, sort_order INT NOT NULL DEFAULT 0, status VARCHAR(16) NOT NULL DEFAULT 'active', create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (category_id), UNIQUE KEY uk_av_discovery_category_name (name), CHECK (status IN ('active','inactive'))) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS av_discovery_tag (tag_id BIGINT NOT NULL, name VARCHAR(64) NOT NULL, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (tag_id), UNIQUE KEY uk_av_discovery_tag_name (name)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS av_workflow_template (template_id BIGINT NOT NULL, tenant_id BIGINT NOT NULL DEFAULT 0, channel VARCHAR(32) NOT NULL, name VARCHAR(128) NOT NULL, slug VARCHAR(128) NOT NULL, summary VARCHAR(512) NULL, description MEDIUMTEXT NULL, cover_asset_id BIGINT NULL, category_id BIGINT NULL, tags_json JSON NULL, form_schema_json JSON NOT NULL, schema_hash CHAR(71) NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'draft', recommended TINYINT NOT NULL DEFAULT 0, sort_no INT NOT NULL DEFAULT 0, estimated_duration_seconds INT NULL, billing_mode VARCHAR(16) NOT NULL DEFAULT 'free', enabled_at DATETIME NULL, execution_relevant_updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, row_revision BIGINT NOT NULL DEFAULT 0, create_by BIGINT NULL, update_by BIGINT NULL, del_flag CHAR(1) NOT NULL DEFAULT '0', create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (template_id), UNIQUE KEY uk_av_workflow_template_tenant_name (tenant_id,name), UNIQUE KEY uk_av_workflow_template_tenant_slug (tenant_id,slug), CONSTRAINT ck_av_workflow_template_channel CHECK (channel IN ('video_template','workflow_inspiration')), CONSTRAINT ck_av_workflow_template_status CHECK (status IN ('draft','pending_test','enabled','disabled')), CONSTRAINT ck_av_workflow_template_recommended CHECK (recommended IN (0,1)), CONSTRAINT ck_av_workflow_template_billing_mode CHECK (billing_mode IN ('free'))) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS av_runninghub_account (account_id BIGINT NOT NULL, tenant_id BIGINT NOT NULL DEFAULT 0, account_name VARCHAR(128) NOT NULL, api_key_ciphertext TEXT NOT NULL, api_key_masked VARCHAR(128) NOT NULL, enabled TINYINT NOT NULL DEFAULT 0, last_health_status VARCHAR(16) NOT NULL DEFAULT 'unknown', last_health_time DATETIME NULL, last_health_summary VARCHAR(512) NULL, credential_updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, row_revision BIGINT NOT NULL DEFAULT 0, create_by BIGINT NULL, update_by BIGINT NULL, del_flag CHAR(1) NOT NULL DEFAULT '0', active_account_name VARCHAR(128) GENERATED ALWAYS AS (CASE WHEN del_flag = '0' THEN account_name ELSE NULL END) STORED, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (account_id), UNIQUE KEY uk_av_runninghub_account_tenant_name (tenant_id,active_account_name), CONSTRAINT ck_av_runninghub_account_enabled CHECK (enabled IN (0,1)), CONSTRAINT ck_av_runninghub_account_health CHECK (last_health_status IN ('unknown','healthy','unhealthy'))) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS av_workflow_execution_config (execution_config_id BIGINT NOT NULL, tenant_id BIGINT NOT NULL DEFAULT 0, template_id BIGINT NOT NULL, runninghub_account_id BIGINT NOT NULL, access_password_ciphertext TEXT NULL, execution_mode VARCHAR(32) NOT NULL, workflow_id VARCHAR(128) NULL, webapp_id VARCHAR(128) NULL, instance_type VARCHAR(16) NULL, input_mapping_json JSON NOT NULL, output_policy_json JSON NOT NULL, timeout_seconds INT NOT NULL DEFAULT 21600, enabled TINYINT NOT NULL DEFAULT 0, last_test_status VARCHAR(16) NOT NULL DEFAULT 'never', last_test_task_id BIGINT NULL, last_test_template_revision BIGINT NULL, last_test_execution_revision BIGINT NULL, last_test_account_revision BIGINT NULL, last_test_time DATETIME NULL, last_test_summary VARCHAR(512) NULL, row_revision BIGINT NOT NULL DEFAULT 0, create_by BIGINT NULL, update_by BIGINT NULL, del_flag CHAR(1) NOT NULL DEFAULT '0', create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (execution_config_id), CONSTRAINT uk_av_workflow_execution_config_template UNIQUE (tenant_id,template_id), CONSTRAINT ck_av_workflow_execution_config_last_test_status CHECK (last_test_status IN ('never','running','success','failed')), CONSTRAINT ck_av_workflow_execution_config_mode CHECK ((execution_mode = 'runninghub_workflow' AND workflow_id IS NOT NULL AND webapp_id IS NULL) OR (execution_mode = 'runninghub_ai_app' AND webapp_id IS NOT NULL AND workflow_id IS NULL)), CONSTRAINT ck_av_workflow_execution_config_enabled CHECK (enabled IN (0,1)), CONSTRAINT ck_av_workflow_execution_config_timeout CHECK (timeout_seconds > 0)) ENGINE=InnoDB;

-- Reconcile column types for databases initialized by an earlier revision of this migration.
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='av_workflow_template' AND column_name='description' AND (data_type<>'mediumtext' OR is_nullable<>'YES')),'ALTER TABLE av_workflow_template MODIFY COLUMN description MEDIUMTEXT NULL','SELECT 1'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='av_runninghub_account' AND column_name='api_key_ciphertext' AND (data_type<>'text' OR is_nullable<>'NO')),'ALTER TABLE av_runninghub_account MODIFY COLUMN api_key_ciphertext TEXT NOT NULL','SELECT 1'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='av_workflow_execution_config' AND column_name='access_password_ciphertext' AND (data_type<>'text' OR is_nullable<>'YES')),'ALTER TABLE av_workflow_execution_config MODIFY COLUMN access_password_ciphertext TEXT NULL','SELECT 1'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
CREATE TABLE IF NOT EXISTS av_workflow_order (order_id BIGINT NOT NULL, tenant_id BIGINT NOT NULL DEFAULT 0, order_no VARCHAR(64) NOT NULL, workspace_id BIGINT NOT NULL, owner_user_id BIGINT NOT NULL, template_id BIGINT NOT NULL, task_id BIGINT NULL, idempotency_key VARCHAR(128) NOT NULL, schema_hash VARCHAR(71) NOT NULL, input_payload_json JSON NOT NULL, request_hash CHAR(64) NOT NULL, billing_mode VARCHAR(16) NOT NULL DEFAULT 'free', usage_operation_id BIGINT NULL, template_title_snapshot VARCHAR(128) NOT NULL, template_cover_snapshot_json JSON NULL, input_display_snapshot_json JSON NOT NULL, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (order_id), UNIQUE KEY uk_av_workflow_order_no (tenant_id,order_no), CONSTRAINT uk_av_workflow_order_idempotency UNIQUE (tenant_id,workspace_id,owner_user_id,idempotency_key), CONSTRAINT ck_av_workflow_order_billing_mode CHECK (billing_mode IN ('free')), CONSTRAINT ck_av_workflow_order_usage_operation CHECK (usage_operation_id IS NULL)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS av_workflow_task_execution (workflow_task_execution_id BIGINT NOT NULL, task_id BIGINT NOT NULL, tenant_id BIGINT NOT NULL DEFAULT 0, runninghub_account_id BIGINT NOT NULL, order_id BIGINT NULL, resource_type VARCHAR(32) NOT NULL, execution_mode VARCHAR(32) NOT NULL, external_task_id VARCHAR(128) NULL, submission_state VARCHAR(32) NOT NULL DEFAULT 'not_started', submission_started_at DATETIME NULL, submitted_at DATETIME NULL, provider_deadline_at DATETIME NULL, last_polled_at DATETIME NULL, poll_count INT NOT NULL DEFAULT 0, external_status VARCHAR(64) NULL, provider_error_code VARCHAR(64) NULL, provider_error_summary VARCHAR(512) NULL, provider_duration_ms BIGINT NULL, provider_usage_json JSON NULL, cost_reconciliation_status VARCHAR(16) NOT NULL DEFAULT 'not_reported', result_manifest_json JSON NULL, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (workflow_task_execution_id), CONSTRAINT uk_av_workflow_task_execution_task UNIQUE (task_id), CONSTRAINT uk_av_workflow_task_execution_external UNIQUE (runninghub_account_id,external_task_id), CONSTRAINT ck_av_workflow_task_execution_mode CHECK (execution_mode IN ('runninghub_workflow','runninghub_ai_app')), CONSTRAINT ck_av_workflow_task_execution_submission CHECK (submission_state IN ('not_started','submitting','accepted','unknown','finished')), CONSTRAINT ck_av_workflow_task_execution_cost_reconciliation CHECK (cost_reconciliation_status IN ('not_reported','reported','unknown')), CONSTRAINT ck_av_workflow_task_execution_resource CHECK ((resource_type = 'workflow_order' AND order_id IS NOT NULL) OR (resource_type = 'workflow_template' AND order_id IS NULL))) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS av_workflow_order_asset (order_asset_id BIGINT NOT NULL, tenant_id BIGINT NOT NULL DEFAULT 0, owner_user_id BIGINT NOT NULL, workspace_id BIGINT NOT NULL, order_id BIGINT NOT NULL, asset_id BIGINT NOT NULL, asset_role VARCHAR(16) NOT NULL, input_key VARCHAR(128) NULL, asset_position_key VARCHAR(128) GENERATED ALWAYS AS (COALESCE(input_key,'')) STORED, sort_order INT NOT NULL DEFAULT 0, is_primary TINYINT NOT NULL DEFAULT 0, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (order_asset_id), UNIQUE KEY uk_av_workflow_order_asset (order_id,asset_role,asset_position_key,sort_order,asset_id), CONSTRAINT ck_av_workflow_order_asset_role CHECK (asset_role IN ('input','output')), CONSTRAINT ck_av_workflow_order_asset_primary CHECK (is_primary IN (0,1)), CONSTRAINT ck_av_workflow_order_asset_input_key CHECK ((asset_role = 'input' AND input_key IS NOT NULL) OR (asset_role = 'output' AND input_key IS NULL))) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS av_file_object (file_id BIGINT NOT NULL, tenant_id BIGINT NOT NULL DEFAULT 0, workspace_id BIGINT NULL, owner_user_id BIGINT NOT NULL, oss_id BIGINT NULL, object_key VARCHAR(512) NOT NULL, content_type VARCHAR(128) NULL, size_bytes BIGINT NOT NULL DEFAULT 0, sha256 VARCHAR(64) NULL, status VARCHAR(16) NOT NULL DEFAULT 'active', create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (file_id), UNIQUE KEY uk_av_file_object_key (object_key), CHECK (status IN ('active','deleted'))) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS av_upload_session (upload_session_id BIGINT NOT NULL, tenant_id BIGINT NOT NULL DEFAULT 0, workspace_id BIGINT NOT NULL, context_scope VARCHAR(32) NOT NULL, owner_user_id BIGINT NOT NULL, file_id BIGINT NULL, idempotency_key VARCHAR(128) NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'created', expires_at DATETIME NOT NULL, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (upload_session_id), UNIQUE KEY uk_av_upload_session_owner_idempotency (tenant_id,workspace_id,owner_user_id,idempotency_key), CONSTRAINT ck_av_upload_session_context_scope CHECK (context_scope IN ('workflow_order','workflow_template','asset')), CONSTRAINT ck_av_upload_session_status CHECK (status IN ('created','uploading','completed','cancelled','expired'))) ENGINE=InnoDB;

-- Conditional per-column additions use information_schema and PREPARE for MySQL 8 compatibility.
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='av_asset' AND column_name='file_id'),'SELECT 1','ALTER TABLE av_asset ADD COLUMN file_id BIGINT NULL'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='av_asset' AND column_name='thumbnail_file_id'),'SELECT 1','ALTER TABLE av_asset ADD COLUMN thumbnail_file_id BIGINT NULL'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='av_asset' AND column_name='asset_type'),'SELECT 1','ALTER TABLE av_asset ADD COLUMN asset_type VARCHAR(32) NULL'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='av_asset' AND column_name='name'),'SELECT 1','ALTER TABLE av_asset ADD COLUMN name VARCHAR(255) NULL'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='av_asset' AND column_name='source_type'),'SELECT 1','ALTER TABLE av_asset ADD COLUMN source_type VARCHAR(32) NULL'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='av_asset' AND column_name='duration_ms'),'SELECT 1','ALTER TABLE av_asset ADD COLUMN duration_ms BIGINT NULL'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='av_asset' AND column_name='tags_json'),'SELECT 1','ALTER TABLE av_asset ADD COLUMN tags_json JSON NULL'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='av_asset' AND column_name='reference_count'),'SELECT 1','ALTER TABLE av_asset ADD COLUMN reference_count INT NOT NULL DEFAULT 0'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;

-- Replace legacy owner-only task keys/checks with dual actor keys/checks, preserving the four timeline result forms.
ALTER TABLE av_ai_task MODIFY owner_user_id BIGINT NULL;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='av_ai_task' AND index_name='uk_av_ai_task_idempotency'),'ALTER TABLE av_ai_task DROP INDEX uk_av_ai_task_idempotency','SELECT 1'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.table_constraints WHERE table_schema=DATABASE() AND table_name='av_ai_task' AND constraint_name='ck_av_ai_task_actor'),'ALTER TABLE av_ai_task DROP CHECK ck_av_ai_task_actor','SELECT 1'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.table_constraints WHERE table_schema=DATABASE() AND table_name='av_ai_task' AND constraint_name='ck_av_ai_task_free_policy'),'ALTER TABLE av_ai_task DROP CHECK ck_av_ai_task_free_policy','SELECT 1'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.table_constraints WHERE table_schema=DATABASE() AND table_name='av_ai_task' AND constraint_name='ck_av_ai_task_success_result'),'ALTER TABLE av_ai_task DROP CHECK ck_av_ai_task_success_result','SELECT 1'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='av_ai_task' AND index_name='uk_av_ai_task_actor_idempotency'),'SELECT 1','ALTER TABLE av_ai_task ADD CONSTRAINT uk_av_ai_task_actor_idempotency UNIQUE (actor_type, actor_id, idempotency_key)'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.table_constraints WHERE table_schema=DATABASE() AND table_name='av_ai_task' AND constraint_name='ck_av_ai_task_actor'),'SELECT 1','ALTER TABLE av_ai_task ADD CONSTRAINT ck_av_ai_task_actor CHECK ((actor_type=''app_user'' AND owner_user_id IS NOT NULL AND actor_id=owner_user_id) OR (actor_type=''sys_user'' AND owner_user_id IS NULL))'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.table_constraints WHERE table_schema=DATABASE() AND table_name='av_ai_task' AND constraint_name='ck_av_ai_task_free_policy'),'SELECT 1','ALTER TABLE av_ai_task ADD CONSTRAINT ck_av_ai_task_free_policy CHECK (quota_policy_version IN (''timeline-free-1'',''workflow-free-1'') AND estimated_usage=0)'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.table_constraints WHERE table_schema=DATABASE() AND table_name='av_ai_task' AND constraint_name='ck_av_ai_task_success_result'),'SELECT 1','ALTER TABLE av_ai_task ADD CONSTRAINT ck_av_ai_task_success_result CHECK ((task_status <> ''success'' AND result_asset_id IS NULL AND result_schema_version IS NULL AND result_payload_json IS NULL) OR (task_status=''success'' AND ((task_type=''timeline_render'' AND result_asset_id IS NOT NULL AND result_schema_version IS NULL AND result_payload_json IS NULL) OR (task_type IN (''timeline_image_prompt_generate'',''timeline_fancy_text_suggest'',''timeline_subtitle_align'') AND result_asset_id IS NULL AND result_schema_version IS NOT NULL AND result_payload_json IS NOT NULL) OR (task_type IN (''workflow_template_generate'',''workflow_template_test'') AND result_asset_id IS NULL AND result_schema_version IS NOT NULL AND result_payload_json IS NOT NULL))))'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
ALTER TABLE av_ai_task_execution MODIFY owner_user_id BIGINT NULL;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='av_ai_task_execution' AND index_name='uk_av_ai_task_execution_no'),'ALTER TABLE av_ai_task_execution DROP INDEX uk_av_ai_task_execution_no','SELECT 1'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.table_constraints WHERE table_schema=DATABASE() AND table_name='av_ai_task_execution' AND constraint_name='ck_av_ai_task_execution_actor'),'ALTER TABLE av_ai_task_execution DROP CHECK ck_av_ai_task_execution_actor','SELECT 1'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='av_ai_task_execution' AND index_name='uk_av_ai_task_execution_no'),'SELECT 1','ALTER TABLE av_ai_task_execution ADD CONSTRAINT uk_av_ai_task_execution_no UNIQUE (task_id, execution_no)'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.table_constraints WHERE table_schema=DATABASE() AND table_name='av_ai_task_execution' AND constraint_name='ck_av_ai_task_execution_actor'),'SELECT 1','ALTER TABLE av_ai_task_execution ADD CONSTRAINT ck_av_ai_task_execution_actor CHECK ((actor_type=''app_user'' AND owner_user_id IS NOT NULL AND actor_id=owner_user_id) OR (actor_type=''sys_user'' AND owner_user_id IS NULL))'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
ALTER TABLE av_ai_task_attempt MODIFY owner_user_id BIGINT NULL;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='av_ai_task_attempt' AND index_name='uk_av_ai_task_attempt_no'),'ALTER TABLE av_ai_task_attempt DROP INDEX uk_av_ai_task_attempt_no','SELECT 1'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.table_constraints WHERE table_schema=DATABASE() AND table_name='av_ai_task_attempt' AND constraint_name='ck_av_ai_task_attempt_actor'),'ALTER TABLE av_ai_task_attempt DROP CHECK ck_av_ai_task_attempt_actor','SELECT 1'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='av_ai_task_attempt' AND index_name='uk_av_ai_task_attempt_no'),'SELECT 1','ALTER TABLE av_ai_task_attempt ADD CONSTRAINT uk_av_ai_task_attempt_no UNIQUE (task_execution_id, attempt_no)'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl=IF(EXISTS(SELECT 1 FROM information_schema.table_constraints WHERE table_schema=DATABASE() AND table_name='av_ai_task_attempt' AND constraint_name='ck_av_ai_task_attempt_actor'),'SELECT 1','ALTER TABLE av_ai_task_attempt ADD CONSTRAINT ck_av_ai_task_attempt_actor CHECK ((actor_type=''app_user'' AND owner_user_id IS NOT NULL AND actor_id=owner_user_id) OR (actor_type=''sys_user'' AND owner_user_id IS NULL))'); PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;

INSERT IGNORE INTO app_permission (permission_id,permission_code,permission_name,resource_type,action,permission_revision,status,created_by_type,created_by_id,updated_by_type,updated_by_id,create_time,update_time) VALUES (1000032,'aivideo:asset:query','素材查看','asset','query',1,'active','sys_user',1,'sys_user',1,NOW(),NOW()),(1000033,'aivideo:asset:upload','素材上传','asset','upload',1,'active','sys_user',1,'sys_user',1,NOW(),NOW()),(1000034,'aivideo:asset:download','素材下载','asset','download',1,'active','sys_user',1,'sys_user',1,NOW(),NOW());
-- personal_creator (1000101) receives the three app asset permissions.
INSERT IGNORE INTO app_role_permission (id,role_id,permission_id,create_time,update_time) VALUES (1000232,1000101,1000032,NOW(),NOW()),(1000233,1000101,1000033,NOW(),NOW()),(1000234,1000101,1000034,NOW(),NOW());
