import {
  AppstoreOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  AudioMutedOutlined,
  AudioOutlined,
  BellOutlined,
  BookOutlined,
  CheckOutlined,
  ClockCircleOutlined,
  CloseOutlined,
  CopyOutlined,
  DeleteOutlined,
  DownloadOutlined,
  EditOutlined,
  EnvironmentOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  FileImageOutlined,
  FileTextOutlined,
  FolderOpenOutlined,
  HomeOutlined,
  InfoCircleOutlined,
  LeftOutlined,
  LockOutlined,
  MenuFoldOutlined,
  MoreOutlined,
  PauseOutlined,
  PlayCircleOutlined,
  PlaySquareOutlined,
  PlusOutlined,
  ReloadOutlined,
  RightOutlined,
  SaveOutlined,
  ScissorOutlined,
  SearchOutlined,
  ShoppingOutlined,
  StarOutlined,
  TagsOutlined,
  ToolOutlined,
  UndoOutlined,
  UnlockOutlined,
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
  WarningOutlined,
} from '@ant-design/icons';
import React from 'react';

const iconMap = {
  app: AppstoreOutlined,
  arrowLeft: ArrowLeftOutlined,
  arrowRight: ArrowRightOutlined,
  bell: BellOutlined,
  book: BookOutlined,
  check: CheckOutlined,
  clock: ClockCircleOutlined,
  close: CloseOutlined,
  copy: CopyOutlined,
  delete: DeleteOutlined,
  download: DownloadOutlined,
  edit: EditOutlined,
  eye: EyeOutlined,
  eyeOff: EyeInvisibleOutlined,
  film: VideoCameraOutlined,
  food: StarOutlined,
  folder: FolderOpenOutlined,
  home: HomeOutlined,
  image: FileImageOutlined,
  info: InfoCircleOutlined,
  left: LeftOutlined,
  lock: LockOutlined,
  map: EnvironmentOutlined,
  menu: MenuFoldOutlined,
  more: MoreOutlined,
  mute: AudioMutedOutlined,
  pause: PauseOutlined,
  play: PlayCircleOutlined,
  playSquare: PlaySquareOutlined,
  plus: PlusOutlined,
  redo: ReloadOutlined,
  refresh: ReloadOutlined,
  right: RightOutlined,
  save: SaveOutlined,
  scissors: ScissorOutlined,
  search: SearchOutlined,
  shopping: ShoppingOutlined,
  star: StarOutlined,
  tag: TagsOutlined,
  text: FileTextOutlined,
  tool: ToolOutlined,
  undo: UndoOutlined,
  unlock: UnlockOutlined,
  upload: UploadOutlined,
  user: UserOutlined,
  volume: AudioOutlined,
  warning: WarningOutlined,
} as const;

export type StudioIconName = keyof typeof iconMap;

const StudioIcon: React.FC<{ name: StudioIconName }> = ({ name }) => {
  const Icon = iconMap[name];
  return <Icon />;
};

export default StudioIcon;
